#!/usr/bin/env bash
#
# 同步能力目录：从 home-agent-os 的代码 + 线上注册表重新导出，并自检。
#
#   scripts/sync.sh /path/to/home-agent-os            # 导出（含实况）+ 自检 + 提交
#   scripts/sync.sh /path/to/home-agent-os --no-live  # 不拉实况（离线）
#   scripts/sync.sh /path/to/home-agent-os --check    # 只对账（CI）：有漂移则非零退出
#
# 生成物（catalog/ capabilities/ schema/）由导出器写，**不要手改** —— 改能力请改 home-agent-os。
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOS="${1:-}"
shift || true
LIVE="--live"
CHECK=""
for arg in "$@"; do
  case "$arg" in
    --no-live) LIVE="" ;;
    --check) CHECK="--check" ;;
    *) echo "[sync][错误] 未知参数 $arg" >&2; exit 2 ;;
  esac
done

EXPORTER="${HOS}/mac/scripts/export_capability_catalog.py"
if [ -z "${HOS}" ] || [ ! -f "${EXPORTER}" ]; then
  echo "[sync][错误] 用法：scripts/sync.sh /path/to/home-agent-os [--no-live] [--check]" >&2
  echo "              （找不到 ${EXPORTER}）" >&2
  exit 2
fi

echo "[sync] 导出：${HOS} → ${HERE}"
python3 "${EXPORTER}" --out "${HERE}" ${LIVE} ${CHECK}

if [ -n "${CHECK}" ]; then
  exit 0
fi

echo "[sync] 自检"
python3 "${HERE}/tests/catalog-schema.test.py"
if command -v node >/dev/null 2>&1; then
  node --test "${HERE}/tests/"*.test.mjs >/dev/null
  echo "[sync] UI 核心逻辑测试通过"
fi

if [ -d "${HERE}/.git" ]; then
  cd "${HERE}"
  if [ -n "$(git status --porcelain)" ]; then
    git add -A
    commit="${HOS_COMMIT:-}"
    [ -n "${commit}" ] || commit="$(git -C "${HOS}" rev-parse --short HEAD 2>/dev/null || echo unknown)"
    git commit -q -m "chore(catalog): 从 home-agent-os ${commit} 同步能力目录" \
      -m "generated by home-agent-os/mac/scripts/export_capability_catalog.py；本仓库的 catalog/capabilities/ schema/ 均为生成物，请勿手改。"
    echo "[sync] 已提交（git push 请自行确认）"
  else
    echo "[sync] 目录无变化"
  fi
fi
